### ISSUE TITLE
numpy v2 upgrade causing problems

### ISSUE THREAD

**Issue by swelborn** [epics-base/pvaPy#91]
Getting this error when running after a fresh install with:

```sh
conda create -n pvapy python=3.11
conda activate pvapy
conda install pip
pip install pvapy
```

```sh
pvapy-ad-sim-server -cn pvapy:image -nx 128 -ny 128 -dt uint8 -rt 60 -fps 1

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/bl832user/anaconda3/envs/pvapy/bin/pvapy-ad-sim-server", line 5, in <module>
    from pvapy.cli.adSimServer import main
  File "/home/bl832user/anaconda3/envs/pvapy/lib/python3.11/site-packages/pvapy/cli/adSimServer.py", line 296, in <module>
    class AdSimServer:
  File "/home/bl832user/anaconda3/envs/pvapy/lib/python3.11/site-packages/pvapy/cli/adSimServer.py", line 310, in AdSimServer
    'timeStamp' : pva.PvTimeStamp()
AttributeError: _ARRAY_API not found
ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/home/bl832user/anaconda3/envs/pvapy/bin/pvapy-ad-sim-server", line 5, in <module>
    from pvapy.cli.adSimServer import main
  File "/home/bl832user/anaconda3/envs/pvapy/lib/python3.11/site-packages/pvapy/cli/adSimServer.py", line 296, in <module>
    class AdSimServer:
  File "/home/bl832user/anaconda3/envs/pvapy/lib/python3.11/site-packages/pvapy/cli/adSimServer.py", line 310, in AdSimServer
    'timeStamp' : pva.PvTimeStamp()
                  ^^^^^^^^^^^^^^^^^
ImportError: numpy.core.umath failed to import
```

**Comment by sveseli** [comment]
Hmm, I suppose I should have realized that numpy 2.0.0 will not be backwards compatible with 1.x. I'll have to release new set of packages with updated numpy requirements. For now, something like "pip install 'numpy<2.0.0'" would fix the issue.

**Comment by swelborn** [comment]
#92 closed this, unless you want to keep it open for v2
